### ISSUE TITLE
Link to service document page on service show page

### ISSUE THREAD

**Issue by madoleary** [tosdr/edit.tosdr.org#712]
I found myself needing something like this during curation.

**Comment by Vinnl** [comment]
There actually is a "Review documents" button below the list of cases (if a service already has documents assigned to it - otherwise it's "Add a document", I believe). It's sometimes aligned all the way to the left of the page, though, so that needs to be fixed, and if it's not visible at all, feel free to move it to a more intuitive place :)

**Comment by madoleary** [comment]
Ah, ok! I'll take a closer look tomorrow.

**Comment by JesseWeinstein** [comment]
Is this resolved?

**Comment by Vinnl** [comment]
I guess so, there's a "View Documents" link just below the service name now.
