### ISSUE TITLE
More uncrawlable documents

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/edit.tosdr.org#723]
https://edit.tosdr.org/documents/567?crawl=true and 568 show up empty.

**Comment by DenishKakadiya** [comment]
I opened documents/568 and click on crawl document button. Now it had crawled document and showing the document. I have faced same issue with many documents, and trying "crawl document" again and again works sometimes.
![Screenshot_2019-04-12 Terms of Service; Didn't Read - Phoenix](https://user-images.githubusercontent.com/25260231/56028766-7b507b80-5d36-11e9-9c77-8876e2d63eeb.png)

**Comment by madoleary** [comment]
The logs show these errors as a series of out-of-memory issues. Can we find a way to improve how the parser functions on the server-side, @michielbdejong? Also, @DenishKakadiya, are you sure you've got the good URL and/or XPath?

**Comment by DenishKakadiya** [comment]
> Also, @DenishKakadiya, are you sure you've got the good URL and/or XPath?
I don't know how to change XPath for already added/crawled document. Hence i did not change it. I just pressed "crawl document" button and it crawled document(though not properly). The unnecessary extra stuff shown crawled document are due to bad XPath.

**Comment by madoleary** [comment]
@DenishKakadiya Okay. This needs closer investigation. It's not a new problem, as you've discovered. I should note that I work on TOSDR in my free time and have a different full-time job. It's the same for the other developers on our team. So solutions may take some time. If you have Ruby on Rails knowledge, feel free to explore the source code, if you want!

**Comment by madoleary** [comment]
(as discussed via email): I just implemented some fixes in production. From now on, you should be able to update and delete the documents that you create. If you want me to give you this ability for the documents that you've created prior to now, please direct me to those documents. I discovered another error, which may or may not be related to the errors you were experiencing the other week. Basically whenever our crawler was unable to reach a webpage (due to an incorrect URL), it would return a 404 error, which would then trigger an error in the server, hence the time-out. This shouldn't happen anymore, and you should receive a specific error message when the crawler can't reach a webpage. 

I'm going to leave this open for now in case other errors arise.

**Comment by JesseWeinstein** [comment]
Another uncrawable one: https://edit.tosdr.org/documents/1467 ; pointing to https://www.usecu.org/bridge/disclosures/ce/ft/termsandconditions.html . I'd love to see what the logs say.

**Comment by JustinBack** [comment]
This has been fixed with the new crawler (above documents have been crawled)
