### ISSUE TITLE
Point 970: how to handle points that don't have a relevant excerpt? 

### ISSUE THREAD

**Issue by madoleary** [tosdr/edit.tosdr.org#729]
The point says:

The underlying software is ownCloud, http://owncloud.org, open source 
under AGPLv3+, http://gitorious.org/owncloud/owncloud 

There's no information about copyright, open source, or licensing in the documents that we have for this service. But it is true that the source code is available at that gitorious link. How should this type of situation be handled?

**Comment by michielbdejong** [comment]
you can just leave the point without an excerpt, right?
add a comment saying 'not adding an excerpt to this one', so that the person approving your points knows that you left it like that on purpose.

there's still a button to create a point without an excerpt, but Vincent hid it somewhere (i think at the bottom of the annotate page)

**Comment by michielbdejong** [comment]
also something for the backloggers guide, maybe

**Comment by madoleary** [comment]
Okay, will just leave some of these without an excerpt.
