### ISSUE TITLE
Signup blocked due to ReCAPTCHA

### ISSUE THREAD

**Issue by Christian-Schiffer** [tosdr/edit.tosdr.org#767]
_First off, please forgive me if this post is outside the accepted guidelines or code of conduct, its my first time posting here and also since I am not at all an experienced GitHub contributor. I also hope the questions raised below are appropriate in this context. In return for your understanding, I am very open to and promise to be grateful for guidance as well as constructive criticism in that respect._

**Issue**: I tried to signup with ToS;DR yet my signup was blocked since I use several adblockers including DuckDuckGo and ToS;DR blocking google and google is the provider of ReCAPTCHA, a valuable service you use to fight spam. That of course is quite an oxymoron given you with good reason criticize google and others for violating our privacy.

**Context**: _I would like to signup since I am about to start a business providing advanced CRM's to my customers. I would very much like to find a way to do so being A rated by you guys since I am all for privacy. Yet the other hand I recognize there are business issues involved and as a businessman I need to if necessary prioritize business over ideology, I am after all not able to work at a loss, no one is._ 

That is why I want to sign up with you as I am looking to find ways to do both, to be profitable and protect my customers as well as my and my customers users privacy. I am hoping signing up with you can help me with finding ways to do just that. 

Now google provides some great services, like ReCAPTCHA, Angular and Material, so part of this discussion of course will be how to separate the good from the bad. I after all do have an Angular / Angular material frontend on my site ( -> currently under development -> https://www.servicelayer.no/ ). That too of course is an oxymoron given I oppose many of googles business practices. I would also like to offer sign in with Facebook / Google / Microsoft to my customers and users, yet another oxymoron.

**Back to the topic**, Possible solutions: Can we develop our own ReCAPTCHA service? What about sign in with Google, Facebook ++? Can we create an OpenID JWT secured service as a true alternative to these actors, what is needed to accomplish that?

TODO: This might need to be split up into several topics?

**Comment by christalib** [comment]
Hello @Christian-Schiffer!

You're not out of the guidelines nor the code of conduct, don't worry.

> Issue: I tried to signup with ToS;DR yet my signup was blocked since I use several adblockers including DuckDuckGo and ToS;DR blocking google and google is the provider of ReCAPTCHA, a valuable service you use to fight spam. That of course is quite an oxymoron given you with good reason criticize google and others for violating our privacy.

We are aware of that. The ReCAPTCHA implementation is a *temporary* one as we were under heavy spam and this sounded to us like the fastest and most efficient solutions. We are going to fix some of our code to prevent that from happening and hoping to move away from ReCAPTACHA as  soon as possible.

> Back to the topic, Possible solutions: Can we develop our own ReCAPTCHA service? What about sign in with Google, Facebook ++? Can we create an OpenID JWT secured service as a true alternative to these actors, what is needed to accomplish that?

That would be a great idea and I think I've heard about projects looking into that but I can't remember now. However, this is not ToS;DR goal nor priorities at the moment. We are a small team of volunteers and we prefer to focus on the tool and the content of our project.

> Context: I would like to signup since I am about to start a business providing advanced CRM's to my customers. I would very much like to find a way to do so being A rated by you guys since I am all for privacy. 

In order to be A rated, you'd need people to rate your service. The code is made as you cannot vote for your own points (analysis) but need other curators of the project to approved your ratings. We don't provide a "What you should do" list, however you could use [this checklist](https://github.com/tosdr/tosdr.org/wiki/checklist) as a more general boilerplate. 

I hope I answered your queries :)

**Comment by Christian-Schiffer** [comment]
Thanks, that pretty much answered most of my current questions. I'll keep your checklist at hand during the development phase and also when making business decisions. The list contain valid concerns, concerns I as a user have too. 

On the business side though, I do see some challenges. As an example, one of the sites I will create with my system is a dating site, deleting one users interaction with another user of course represents a legal challenge and a possible security concern for my users. So there is that too...

**Comment by LeoNatan** [comment]
🎅🤡
