### ISSUE TITLE
Unable to add a service

### ISSUE THREAD

**Issue by arthurlutz** [tosdr/edit.tosdr.org#769]
When trying to add a service, I first get redirected to the same form with title empty. When I re-enter the title and re-submit the service, I get a white page with "retry later" 

By the way, why do we need a recaptcha (working freely for google) on this form when authenticated ?

**Comment by michielbdejong** [comment]
We had some issues with vandalism and decided to add captchas as a stop gap  (we're aware it's not a perfect solution!).

@madoleary do you think the  'retry later' text is coming from the captcha in this case?

**Comment by madoleary** [comment]
This is from our rate-limiting protections, since the same vandal was creating hundreds and hundreds of phony services in a very short time period. You can create one service every 10 minutes.

**Comment by arthurlutz** [comment]
Ok for the "every 10 minutes", maybe the message should include this information ?

**Comment by madoleary** [comment]
I agree :) I can get this added this weekend. Thanks for the feedback.

**Comment by madoleary** [comment]
So I've added a more descriptive error message. I've also bumped up the limit to two services every 10 minutes. However, I'm still confused by your initial problem with the title. So, you tried to create a service, but didn't include a title, so the form rendered again, at which point you filled in the title, but then it wouldn't let you re-submit the form due to the rate-limiting error? And was this after you had already successfully created one service? If so, then the rate-limitation was working as intended. However, you should have seen some time of error message render on the form for a missing title. Did you see this little red message?
