### ISSUE TITLE
Should points be rejected because they do not use a service's ToS/Privacy Policy?

### ISSUE THREAD

**Issue by hondarevie** [tosdr/edit.tosdr.org#789]
For example, 

- an open source service has a commit made that would support one of the cases (like using third-party analytics)
- a post on a service's forums by one of the staff giving information about their security practices

I know the TOSDR has an option to add a point not linked to a posted document, but there is a curator who is marking points as "changes-requested" because it is from content not used in an official document such as a terms of service.

**Comment by madoleary** [comment]
Hi! 

I believe there's been some confusion about this in the past, which could have led to some points being marked in this way, but in general, yes, TOSDR supports points that don't explicitly originate from the ToS/Privacy Policy, as long as the source is specified in the description or otherwise provided and described during point submission. 

Would you be able to direct me to these points? You can respond here or email team@tosdr.org. If they're all occurring for a specific service, feel free to respond here with the name of the service.

**Comment by hondarevie** [comment]
https://edit.tosdr.org/points/6207

**Comment by madoleary** [comment]
Thanks, just took a look. Marked as approved.
