### ISSUE TITLE
500 errors on API endpoints

### ISSUE THREAD

**Issue by ayusun** [tosdr/edit.tosdr.org#864]
I was going through the documents and found the need to update the WIKI page (specifically the API URL)

https://github.com/tosdr/edit.tosdr.org/wiki/api

**Comment by michielbdejong** [comment]
Fixed, thanks!

I do see there's an internal server error on https://edit.tosdr.org/api/v1/points and http://edit.tosdr.org/api/v1/services (but not on https://edit.tosdr.org/api/v1/topics). Could it be that we now have so many points and services that the server runs out of memory.

From the Heroku logs:
2019-10-07T08:48:08.857693+00:00 heroku[web.1]: Process running mem=542M(105.9%)
2019-10-07T08:48:08.857752+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)

Running `heroku restart --app edit-tosdr-org` made the memory usage drop from 540Mb to 120Mb but the 500 errors remain.

**Comment by michielbdejong** [comment]
Oh, I had forgotten that we added an API to edit.tosdr.org, are you using it? Would it make senes for you to use the API of the main tosdr.org site instead? If you need access to the edit.tosdr.org discussions then we can fix its API of course, but would like to understand your use case first.

**Comment by tringm** [comment]
Thank you for answering!
The reason I'm looking at the edit.tosdr.org API is that it has the URL to the original document, instead of just the document name in the tosdr.org API. For instance, [Facebook point 743](https://edit.tosdr.org/points/743), and the [Tosdr API Facebook](https://tosdr.org/api/1/service/facebook.json) does not contain the link to "What information does Facebook get when I visit a site with the Like button?". I assume that the original doc URL would be maintained so this would really help with crawling the content of the original document.
The use case I'm working on a Hybrid Machine Translation Model that is able to highlight important pieces of information in a legal doc (the `quoteText`), and translate it to human-readable summary (the `tosdr.case`). This would help the human resource needed to manually read the tos. The training data for the model would be the original tos doc, which requires the original document URL.

**Comment by madoleary** [comment]
I was looking through our issues and wanted to follow up: the endpoints for Edit have been fixed, referenced here #938 and here #941. Sorry for the delay.
