### ISSUE TITLE
Phoenix API results in server error

### ISSUE THREAD

**Issue by JustinBack** [tosdr/edit.tosdr.org#938]
Wether indexing or retrieving points or services, the results all end in a Server Error
![grafik](https://user-images.githubusercontent.com/40178814/97258634-1e81bc80-1819-11eb-8fc7-d17091b623e6.png)

**Comment by cherryblossom000** [comment]
I'm not sure if this related but a 503 error occurs with https://edit.tosdr.org/services/list_all. Because this is used by https://edit.tosdr.org/services viewing the services doesn't work:

![screenshot of failed network request](https://user-images.githubusercontent.com/31467609/98520058-ac53b200-22c5-11eb-9eae-ac427ce898bf.png)

<details>
<summary>Response</summary>

```html
<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>
```

</details>

**Comment by JustinBack** [comment]
> I'm not sure if this related but a 503 error occurs with https://edit.tosdr.org/services/list_all. Because this is used by https://edit.tosdr.org/services viewing the services doesn't work:
> 
> ![screenshot of failed network request](https://user-images.githubusercontent.com/31467609/98520058-ac53b200-22c5-11eb-9eae-ac427ce898bf.png)
> 
> Response


Could be that rails or heroku is slow, we have that issue a lot

**Comment by madoleary** [comment]
Hey there, sorry about the delay. It's been fixed.

**Comment by madoleary** [comment]
Just for posterity, `list_all` and the services index endpoint for the API are two different things. Indeed, there are quite a lot of service objects being called up at once from the database when that page is loaded. It certainly tends to slow things down. In the near future I'd like to implement a type of progressive scroll, so that the services are loaded as the user's eye-line moves down the page.

**Comment by JustinBack** [comment]
Well services are working properly now however point indexes are still broken
![grafik](https://user-images.githubusercontent.com/40178814/98572438-ec129d80-22b5-11eb-9bbe-7cb2aab7f1d6.png)

**Comment by madoleary** [comment]
Reopened the issue, will deploy a fix shortly.

**Comment by madoleary** [comment]
It's working now; the JSON response is enormous. Would some type of pagination be useful? Leaving this open for other API suggestions.

**Comment by JustinBack** [comment]
Yes pagination would be useful or a ?limit= parameter, would also need the max page count in the json then

**Comment by madoleary** [comment]
Sure, I'm not gonna be able to get to it tonight, but I will work on it
this week.

**Comment by JustinBack** [comment]
Alright, no worries. Not in need of it right now, we need a case api though. I have opened an issue for this  #941

**Comment by madoleary** [comment]
Oh, okay. I can get to that, also.
